//
//  Generated by pegged $Version
//  Fork: https://github.com/hydrixos/pegged
//

#import <Foundation/Foundation.h>

//!$OtherClasses

/*!
 @abstract The ParserClass public interface
 */
@interface ParserClass : NSObject

//!$Properties

/*!
 @abstract Parses the given string.
 @discussion Returns YES on match.
 */
- (BOOL) parseString:(NSString *)string;

@end



/*!
 @abstract Methods available for parser actions
 */
@interface ParserClass (ParserActionHelper)


#pragma mark - Parser state

/*!
 @abstract The start index of the current capture
 */
@property (readonly) NSUInteger captureStart;

/*!
 @abstract The end index of the current capture
 */
@property (readonly) NSUInteger captureEnd;

/*!
 @abstract The currently parsed string
 */
@property (readonly) NSString* string;



#pragma mark - Action helpers

/*!
 @abstract Provides a result for the current rule
 */
- (void)pushResult:(id)result;

/*!
 @abstract Accesses the next result of a sub-rule
 */
- (void)nextResult;

/*!
 @abstract Accesses the result of a sub-rule with a certain index
 */
- (void)resultAtIndex:(NSInteger)index;

/*!
 @abstract Provies all sub-rule results as array.
 */
- (NSArray *)allResults;

@end