//
//  Generated by pegged 0.4.1
//  Fork: https://github.com/hydrixos/pegged
//

#import <Foundation/Foundation.h>


@class Compiler;

@class PEGParser;


@protocol PEGParserDataSource;
typedef NSObject<PEGParserDataSource> PEGParserDataSource;
typedef BOOL (^PEGParserRule)(PEGParser *parser);
typedef void (^PEGParserAction)(PEGParser *self, NSString *text);

@interface PEGParser : NSObject

@property (strong) PEGParserDataSource *dataSource;


@property (readonly) NSUInteger captureStart;
@property (readonly) NSUInteger captureEnd;
@property (readonly) NSString* string;
@property (strong) Compiler *compiler;


- (BOOL) parse;
- (BOOL) parseString:(NSString *)string;

@end


@protocol PEGParserDataSource

- (NSString *) nextString;

@end
