//
//  Generated by pegged 0.4.1
//  Fork: https://github.com/hydrixos/pegged
//

#import <Foundation/Foundation.h>

@class Compiler;


/*!
 @abstract The PEGParser public interface
 */
@interface PEGParser : NSObject

@property (strong) Compiler *compiler;


/*!
 @abstract Parses the given string.
 @discussion Returns YES on match.
 */
- (BOOL) parseString:(NSString *)string;

@end
